### ISSUE TITLE
ALLOW Options not allowing docker stop

### ISSUE THREAD

**Issue by seanob86** [linuxserver/docker-socket-proxy#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`HTTP 403 Forbidden` received when trying to stop containers behind docker socket. Environment variables configured like below

```
    environment:
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTARTS=1
      - CONTAINERS=1
      - POST=0
```

additionally `- POST=1` would normally allow containers to stop (which works in the technativa image), however this fails in lsio image. 

Docker API version is `1.47`

According to docs this should work while `POST=0`, however also fails when `POST=1`

container image used is from `latest` tag. Just in-case there was a more up-to-date version I attempted to pull `latest` again, but image was already up-to-date. 

### Expected Behavior

Should allow interaction with commands such as `docker stop [container]` while `- POST=0`, but doesn’t. 

Also fails with `POST=1`

### Steps To Reproduce

```
    environment:
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTARTS=1
      - CONTAINERS=1
      - POST=0
```

### Environment

```markdown
OS: Debian GNU/Linux 12 (bookworm)

Docker/Compose installed via apt install per docker documentation

Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:11 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:11 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.24
  GitCommit:        88bf19b2105c8b17560993bee28a01ddc2f97182
 runc:
  Version:          1.2.2
  GitCommit:        v1.2.2-0-g7cb3632
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker creation

```bash
dockersocket:
    container_name: dockersocket
    image: lscr.io/linuxserver/socket-proxy:latest
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket
    environment:
      CONTAINERS: 1
      ALLOW_START: 1
      ALLOW_STOP: 1
      POST: 0
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
```
```


### Container logs

On client issuing docker stop command: `<html><body><h1>403 Forbidden</h1>`

**Comment by thespad** [comment]
OK, found the issue. ALLOW_RESTARTS was catching the `stop` command before it could get to the ALLOW_STOP block and causing it to return a 403. I'll work up a PR to fix the behaviour.
